version: "3.8"

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailhog
    environment:
      - DB_HOST=db
      - DB_DATABASE=imobiliaria_formulario
      - DB_USERNAME=admin
      - DB_PASSWORD=123

  db:
    image: mysql:8.0
    container_name: mysql_db_formulario
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: imobiliaria_formulario
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
