name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: imobiliaria_formulario
          MYSQL_USER: admin
          MYSQL_PASSWORD: 123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo_mysql, tokenizer
          coverage: none

      - name: Install Composer dependencies
        working-directory: ./src
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Wait for MySQL
        run: |
          for i in {30..0}; do
            php -r "new PDO('mysql:host=mysql;dbname=imobiliaria_formulario','admin','123');" && break
            echo 'MySQL not ready yet...'
            sleep 2
          done

      - name: Generate application key
        working-directory: ./src
        run: php artisan key:generate

      - name: Run migrations
        working-directory: ./src
        run: php artisan migrate --force

      - name: Run tests
        working-directory: ./src
        run: php artisan test
